### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by hanscg** [dimaqq/dynalite-docker#10]
Hey @dimaqq, we talked in the team and thinks that we can take over the maintenance of this repo and move it to HENNGE account.
Do you mind if we do so?

**Comment by dimaqq** [comment]
No problem, will be happy to pass this over.
I guess, in practice, both docker hub and ghcr are now under my acct.
So, just fork the repo and start publishing the images under your own namespace 🎉

**Comment by hanscg** [comment]
Sorry for the late reply. 
Got it, I'll try to fork it, thank you!

**Comment by hanscg** [comment]
Forked and released to ghcr.io
I'll close this issue, thank you! 🙇 
https://github.com/HENNGE/dynalite-docker
